# Generated by Django 3.1.4 on 2020-12-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCNN', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagen',
            new_name='TablaFlores',
        ),
    ]
